{"success": true, "data": [{"team": {"name": "Unknown Exception", "id": 968}, "date": "2023-08-26T18:36:25.497559+00:00", "challenge_id": 1, "challenge": {"name": "\u25b6 Sanity Check", "category": "Misc", "value": 39, "id": 1}, "user": {"name": "notemax", "id": 1935}, "type": "correct", "id": 6177}], "meta": {"count": 1}}
